### ISSUE TITLE
Expose as Helm repo

### ISSUE THREAD

**Issue by zhelyan** [Kurt108/helm-gotenberg#1]
Hi,

thanks for the chart!
Could you please publish it as a helm repo using e.g. GH pages?
Happy to open a PR if you create a gh pages branch.

**Comment by kurt---** [comment]
Hi @zhelyan 

I will update the repo and publish it using Gh Pages. but I guess I will be able to do that next week.

kurt

**Comment by kurt---** [comment]
I just created the gh-pages branch

**Comment by zhelyan** [comment]
Thanks, I opened a pr to gh-pages, once merged you can enable GH pages in the repo settings

**Comment by Kurt108** [comment]
I needed to rename my username because kurt--- is not a valid DNS-Name. But now you can try https://kurt108.github.io/helm-gotenberg/

thx a lot for your MR

Kurt
